import java.util.Arrays;
import java.util.HashMap;
import java.util.Map;

/*
 * Given two strings s and t which consist of only lowercase letters.
 * String t is generated by random shuffling string s and then add one more letter at a random position.
 * Find the letter that was added in t.
 * 
 */

public class FindTheDifference {
    public char findTheDifference(String s, String t) {
    	char result = 'a';
    	char[] sArray = s.toCharArray();
    	char[] tArray = t.toCharArray();
    	Map<String, Integer> occurence = new HashMap<String, Integer>();
    	
    	for (int i = 0; i < tArray.length; i++) {
    		String processChar = tArray[i] + "";
    		if (!occurence.containsKey(processChar)) {
    			occurence.put(processChar, 1);
    		}
    		else {
    			occurence.put(processChar, occurence.get(processChar) + 1);
    		}
    	}
    	
    	for (int i = 0; i < sArray.length; i++) {
    		String processChar = sArray[i] + "";
    		if (occurence.containsKey(processChar)) {
    			occurence.put(processChar, occurence.get(processChar) - 1);
    			if (occurence.get(processChar) == 0) {
    				occurence.remove(processChar);
    			}
    		}
    	}
    	
    	for (String key : occurence.keySet()) {
    		result = key.charAt(0);
    	}
    	
//    	System.out.println(Arrays.asList(occurence));
    	
//    	Arrays.sort(sArray);
//    	Arrays.sort(tArray);
    	
//    	result = tArray[tArray.length - 1];
     
    	return result;
    }
}
